name: Greeting
on: [push, pull_request]
env:
    test_var: lucas is awesome
    workflow_var: this was defined at the workflow level
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    env:
      test_var: lucas is great
      job_var: this was defined at the job level
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: 'Echo the envs, including test var: " ${{ env.test_var }} "'
        env:
          test_var: lucas is just average
          step_var: this was defined at the step level
        run: echo "this is using envs WITHOUT the context" && echo "$workflow_var" && echo "$job_var" && echo "$step_var" && echo "$test_var"
